services:
  postgres: 
    image: postgres:13
    environment:
      - POSTGRES_DB=blogApp
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test123
    ports: 
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports: 
      - 5050:80
 