services:
  mongo:
    image: initialized-mongo:latest
    ports:
      - "3456:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo_data:/data/db

  redis: 
    image: redis:latest
    ports:
      - "6379:6379"


#URLS
# REDIS_URL=redis://localhost:6379 
# MONGO_URL=mongodb://the_username:the_password@localhost:3456/the_database

#Commands to run
# REDIS_URL=redis://localhost:6379 MONGO_URL=mongodb://the_username:the_password@localhost:3456/the_database npm run dev