services:
  todo-backend:
    image: todo-back-dev
    container_name: todo-back-dev
    build: 
      context: ./todo-backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./todo-backend:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://root:example@mongo:27017/the_database?authSource=admin
    depends_on:
      - mongo
      - redis

  mongo:
    image: initialized-mongo:latest
    ports:
      - "3456:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo_data:/data/db

  redis: 
    image: redis:latest
    ports:
      - "6379:6379"
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data
