### Fetches all blog entries from the API
GET http://localhost:3001/api/blogs

### Filters blog by title content
GET http://localhost:3001/api/blogs?search=quantum

### Filters blog by author
GET http://localhost:3001/api/blogs?search=grace

### Fetches a single blog entry by its ID
GET http://localhost:3001/api/blogs/10

### Create a new blog post
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJAbWFpbC5jb20iLCJpZCI6NSwiaWF0IjoxNzU3NDUyMDU0fQ.2MB8awXlEOUo65wUfE04d4_szNxa5W_JyJsJ0RX3RJ4

{
  "title": "Getting Started with Express.js",
  "author": "Express Team",
  "url": "https://techinsights.com/express-getting-started",
  "likes": 1
}

### Create a blog post with missing fields (should fail)
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Test Author"
}

### Delete a blog post by its ID
DELETE http://localhost:3001/api/blogs/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJAbWFpbC5jb20iLCJpZCI6NSwiaWF0IjoxNzU3MzY4OTc1fQ.UH_pU_j165jWu19gd-4bdMsPUpnPCDa5Yvqs0RkjeUI

### Update the number of likes for a blog post
PUT http://localhost:3001/api/blogs/9
Content-Type: application/json

{
  "likes": 8
}