### Fetches all blog entries from the API
GET http://localhost:3001/api/blogs

### Filters blog by title content
GET http://localhost:3001/api/blogs?search=quantum

### Filters blog by author
GET http://localhost:3001/api/blogs?search=grace

### Fetches a single blog entry by its ID
GET http://localhost:3001/api/blogs/10

### Create a new blog post
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsaWNlQGV4YW1wbGUuY29tIiwiaWQiOjEsImlhdCI6MTc1ODY2NTAxMX0.K-4hh8DnvRm_AT9gkCD4eaSkCGuNARrkQX0ntvhGjOI

{
  "title": "Understanding REST APIs in Node.js",
  "author": "Tech Insights",
  "url": "https://techinsights.com/rest-apis-nodejs",
  "likes": 5,
  "year": 2025
}

### Create a blog post with missing fields (should fail)
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Test Author"
}

### Delete a blog post by its ID
DELETE http://localhost:3001/api/blogs/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsaWNlQGV4YW1wbGUuY29tIiwiaWQiOjEsImlhdCI6MTc1ODY2NTAxMX0.K-4hh8DnvRm_AT9gkCD4eaSkCGuNARrkQX0ntvhGjOI

### Update the number of likes for a blog post
PUT http://localhost:3001/api/blogs/9
Content-Type: application/json

{
  "likes": 8
}