### Get all users
GET http://localhost:3001/api/users

### Get a user by ID
GET http://localhost:3001/api/users/2

### Get a user by ID with 'read' parameter set to true
GET http://localhost:3001/api/users/2?read=true

### Get a user by ID with 'read' parameter set to false
GET http://localhost:3001/api/users/2?read=false

### Create a new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "New User2",
  "username": "user2@mail.com"
}

### Update a user's name by username
PUT http://localhost:3001/api/users/user2@mail.com
Content-Type: application/json

{
  "name": "updated"
}