### GET USERS
GET http://localhost:3003/api/users/

### POST USERS
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "user",
    "password": "passwrd"
}


### LOGIN
POST http://localhost:3003/api/login/
Content-Type: application/json

{
    "username": "user",
    "password": "passwrd"
}


### GET BLOGS
GET http://localhost:3003/api/blogs/

### POST BLOGS from authorized user user
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjY3M2E1NTc2MmMwNTM2ZDYxMzA3NWE3MyIsImlhdCI6MTczMjAxMzUxMCwiZXhwIjoxNzMyMDk5OTEwfQ.1noIuHiLFWX_N8gpkXpZnhzrCc4b8OtnuFF2FMaYe54

{
    "title": "middleware implemented and everything stills working fine",
    "author": "000",
    "url": "mongo.com"
}


### DELETE BLOGS from authorized user user
DELETE  http://localhost:3003/api/blogs/673c84c2374dc19ee9b86fa0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjY3M2E1NTc2MmMwNTM2ZDYxMzA3NWE3MyIsImlhdCI6MTczMjAxMzUxMCwiZXhwIjoxNzMyMDk5OTEwfQ.1noIuHiLFWX_N8gpkXpZnhzrCc4b8OtnuFF2FMaYe54

### ERROR TESTING (user did not create the blog)
DELETE  http://localhost:3003/api/blogs/673914065e26c4c92c7f9eb2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjY3M2E1NTc2MmMwNTM2ZDYxMzA3NWE3MyIsImlhdCI6MTczMjAxMzUxMCwiZXhwIjoxNzMyMDk5OTEwfQ.1noIuHiLFWX_N8gpkXpZnhzrCc4b8OtnuFF2FMaYe54