### Test: Get all notes
GET http://localhost:3001/api/notes


### Test: Get one note
GET http://localhost:3001/api/notes/5


### Test: Create a new note
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOjEsImlhdCI6MTc1NzI3MDM3Mn0.SAI8YMHMo4esHwsChAYRGmfB6L798fd-6EG4nfZIYjA

{
  "title": "Test Note",
  "content": "This is a test note.",
  "important": false
}

### Test: Get a note by ID (replace :id with a real note ID)
GET http://localhost:3001/api/notes/:id
Accept: application/json

### Test: Update a note by ID (replace :id with a real note ID)
PUT http://localhost:3001/api/notes/4
Content-Type: application/json

{
  "important": true
}

### Test: Delete a note by ID (replace :id with a real note ID)
DELETE http://localhost:3001/api/notes/3
Accept: application/json